### ISSUE TITLE
How to get the latest binary which support Marvell Armada?

### ISSUE THREAD

**Issue by hirakujira** [alexandregz/gogs-spk#1]
Tried to copy Linux arm binary which is available on the official website, but my NAS can't run that binary. I'm wondering whether you build your own binary from the source code? If so, what't the parameters of `go build` to set the correct archs?

Thanks

**Comment by hirakujira** [comment]
Never mind, found the way:
`GOOS=linux GOARCH=arm GOARM=7 go get -u github.com/gogits/gogs`

**Comment by alexandregz** [comment]
Nice, thx! :-)

I used the binaries compiled by gogs project itself without problem

I'm going to add the command to compile to README, if you don't mind.
