### ISSUE TITLE
Any update planned?

### ISSUE THREAD

**Issue by olinox14** [alexandregz/gogs-spk#10]
The package worked great for me so far, but maria-db 5 is not supported anymore by synology DSM 7, making this spk obsolete.

Is there any chance for it to be updated with a maria-db 10 dep?

**Comment by alexandregz** [comment]
Unfortunately I don't have a NAS with DSM 7 to test, sorry.

I'm looking to project and I think you only need to change one file to use MariaDB 7: https://github.com/alexandregz/gogs-spk/blob/master/2_create_project/conf/PKG_DEPS

**Comment by olinox14** [comment]
No need to upgrade to DSM 7, the mariadb 10 package is also available on DSM 6
